title: Jatin Gagwani
description: Digital Marketing Architect
url: "https://jatingagwani.com"
baseurl: ""
permalink: /blog/:title/
future: true
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - node_modules
  - "*.sh"
